moul/u

- encoding.go
- encoding_test.go
> feat: add B64{Encode,Decode}

- pattern.go
- pattern_test.go
> feat: add CombineFuncs

- concurrency.go
- concurrency_test.go
> feat: add MonoChild

- concurrency.go
- concurrency_test.go
> feat: rename MonoChild -> UniqueChild + add UniqueChild.CloseChild

- io.go
- io_test.go
> feat: add io stream capture helper

- .gitignore
- AUTHORS
- Makefile
- README.md
> chore: update README

- encoding_test.go
- go.mod
- go.sum
> fix: remove godep dependency

- README.md
- os.go
- os_test.go
> feat: TempfileWithContent

- README.md
- time.go
- time_test.go
> feat: add ShortDuration

- signal.go
- signal_test.go
> feat: add WaitForCtrlC

- os.go
- os_test.go
> feat: add u.ExpandUser

- os.go
- os_test.go
> feat: func {Path,Dir,File}Exists(path string)

- AUTHORS
- README.md
- exec.go
- exec_test.go
> feat: add ExecStandaloneOutputs and SafeExec

- README.md
- os.go
- os_test.go
> feat: u.TempFileName + u.CreateEmptyFileWithSize

- README.md
- exec.go
- exec_test.go
> feat: add u.CommandExists

- .github/workflows/go.yml
- README.md
- sync.go
- sync_test.go
> feat: add MutexMap

- pattern.go
- pattern_test.go
> feat: add CheckErr

- README.md
- encoding_test.go
- exec_test.go
- pattern_test.go
- rand_test.go
- slice_test.go
- time_test.go
> Benchmark Tests

- README.md
- types.go
- types_test.go
> feat: add 'BoolPtr'

- README.md
- os.go
- os_test.go
- path.go
- path_test.go
> feat: add u.ExpandPath

- README.md
- encoding.go
- encoding_test.go
> feat: add u.IsASCII
